apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - image: adamgolab/hello-world
          name: hello-world
          env:
            - name: PORT
              value: "80"
            - name: WORLD
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 80
